# Generated by Django 4.2 on 2023-05-06 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("keys_private", models.CharField(max_length=255)),
                ("keys_public", models.CharField(max_length=255)),
                ("keys_secret", models.CharField(max_length=255)),
                ("fcm_token", models.CharField(max_length=255)),
                ("fcm_pushset", models.CharField(max_length=255)),
                ("gcm_token", models.CharField(max_length=255)),
                ("gcm_androidId", models.BigIntegerField()),
                ("gcm_securityToken", models.BigIntegerField()),
                ("gcm_appId", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
