# Generated by Django 4.2 on 2023-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="gcm_androidId",
            new_name="gcm_androidid",
        ),
        migrations.RenameField(
            model_name="credential",
            old_name="gcm_appId",
            new_name="gcm_appid",
        ),
        migrations.RenameField(
            model_name="credential",
            old_name="gcm_securityToken",
            new_name="gcm_securitytoken",
        ),
    ]
