# Generated by Django 4.2 on 2023-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "address_directory",
            "0002_rename_gcm_androidid_credential_gcm_androidid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="rust_registration_status",
            field=models.BooleanField(default=False),
        ),
    ]
