# Generated by Django 4.2 on 2023-05-15 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address_directory", "0004_alter_credential_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="gcm_securitytoken",
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name="Condata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip", models.CharField(max_length=255)),
                ("playerid", models.CharField(max_length=255)),
                ("playertoken", models.CharField(max_length=255)),
                ("port", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
