# Generated by Django 4.2 on 2023-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0005_alter_credential_gcm_securitytoken_condata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="gcm_androidid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="credential",
            name="gcm_securitytoken",
            field=models.CharField(max_length=255),
        ),
    ]
