# Generated by Django 4.2 on 2023-05-18 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0008_server_server_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
