# Generated by Django 4.2 on 2023-05-18 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0009_server_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="server_num",
            new_name="server_id",
        ),
    ]
