# Generated by Django 4.2 on 2023-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0010_rename_server_num_server_server_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
