# Generated by Django 4.2 on 2023-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0011_server_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="stream",
            field=models.BooleanField(default=False),
        ),
    ]
