# Generated by Django 4.2 on 2023-05-25 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0013_alter_server_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_time", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="server",
            name="stream",
        ),
        migrations.CreateModel(
            name="Guildinfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guild_id", models.CharField(max_length=255, unique=True)),
                ("inviter_id", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                (
                    "notification_settings",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="address_directory.notificationsettings",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="address_directory.server",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
