# Generated by Django 4.2 on 2023-05-26 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "address_directory",
            "0014_notificationsettings_remove_server_stream_guildinfo",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="guildinfo",
            old_name="guild_id",
            new_name="_guild_id",
        ),
    ]
