# Generated by Django 4.2 on 2023-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0016_rename_playerid_server__playerid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="last_message_time",
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
