# Generated by Django 4.2 on 2023-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0017_notificationsettings_last_message_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="show_distance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="show_location",
            field=models.BooleanField(default=False),
        ),
    ]
