# Generated by Django 4.2 on 2023-06-07 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0020_notificationsettings_vend_show_distance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="server",
            options={"ordering": ["date_created"]},
        ),
    ]
