# Generated by Django 4.2 on 2023-06-11 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address_directory", "0021_alter_server_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildinfo",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
