# Generated by Django 4.2 on 2023-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_directory", "0022_guildinfo_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="guildinfo",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
