# Generated by Django 4.2 on 2023-05-06 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="cis_staff",
            new_name="is_staff",
        ),
    ]
